sonar.projectKey=api-dtc-gin-demo
#sonar.projectName=api-dtc-gin-demo
sonar.go.coverage.reportPaths=coverage.out
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/cmd/**,**/deploy/**,**/deploy-templates/**,**/*.groovy,**/config/**
sonar.language=go
sonar.host.url=https://sonarqube.dpm.sdlc.app.cbrands.com
sonar.token=squ_275ff05c0b9f8dd59c967358165fd536b92c83df
sonar.scanner.force-deprecated-java-version=true
