sonar.projectKey=api-dtc-gin-demo
sonar.projectName=api-dtc-gin-demo
sonar.go.coverage.reportPaths=coverage.out
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/cmd/**,**/deploy/**,**/deploy-templates/**,**/*.groovy,**/config/**
sonar.language=go
sonar.host.url=https://sonarqube.dpm.sdlc.app.cbrands.com
sonar.token=squ_9f67e764ec4d03d930b3b80052615dc3be79da23
sonar.scanner.force-deprecated-java-version=true
